# Generated by Django 3.2.16 on 2024-07-30 12:14

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[recipes.validators.not_zero_validator], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipeingredientsamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[recipes.validators.not_zero_validator], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_shoplist'),
        ),
    ]
